---
title: Imbue
timezone: UTC
collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: News
    output: true
baseurl:
url:
markdown: kramdown
phone: "0191 3778358"
email: "info@imbueoffices.co.uk"
img_dir: "/uploads/"
linkedin: https://www.linkedin.com/
github: [metadata]
exclude:
- vendor
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-feed
- github-pages
