---
title: Imbue | Inspirational Office Space
description: We are Imbue - fully serviced office space and room hire available for everyone.
logo: /uploads/imbue-logo.png
lang: en_GB
timezone: UTC
collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: News
    output: true
baseurl:
url: https://www.imbueoffices.co.uk
markdown: kramdown
phone: "0191 389 7062"
email: "info@imbueoffices.co.uk"
img_dir: "/uploads/"
linkedin: https://www.linkedin.com/company/imbue-offices/
exclude:
  - vendor
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-feed
  - github-pages
  - jekyll-redirect-from
  - jekyll-seo-tag
whitelist:
  - jekyll-redirect-from
github: [metadata]
repository: adept-webmaster/imbue
