- title: Onsite Parking Available
  image: icon-parking.svg
- title: CCTV in Operation
  image: icon-cctv.svg
- title: Reception
  image: icon-reception.svg
- title: Fully Adjustable Air Conditioning
  image: icon-ac.svg
- title: Meetings and Boardrooms Available
  image: icon-boardroom.svg
- title: LED Lighting System
  image: icon-lighting.svg
